name: Documentation

on:
  pull_request:
    paths:
      - "docs/**"
      - "*.md"

permissions:
  contents: read

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Documentation Check
        run: |
          echo "Documentation updated successfully."